// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file pic.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _PIC_H_
#define _PIC_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(pic_SOURCE)
#define pic_DllAPI __declspec( dllexport )
#else
#define pic_DllAPI __declspec( dllimport )
#endif // pic_SOURCE
#else
#define pic_DllAPI
#endif
#else
#define pic_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure pic defined by the user in the IDL file.
 * @ingroup PIC
 */
class pic
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport pic();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~pic();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object pic that will be copied.
     */
    eProsima_user_DllExport pic(const pic &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object pic that will be copied.
     */
    eProsima_user_DllExport pic(pic &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object pic that will be copied.
     */
    eProsima_user_DllExport pic& operator=(const pic &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object pic that will be copied.
     */
    eProsima_user_DllExport pic& operator=(pic &&x);

    /*!
     * @brief This function copies the value in member img
     * @param _img New value to be copied in member img
     */
    inline eProsima_user_DllExport void img(const std::array<std::array<char, 1080>, 1920> &_img)
    {
        m_img = _img;
    }

    /*!
     * @brief This function moves the value in member img
     * @param _img New value to be moved in member img
     */
    inline eProsima_user_DllExport void img(std::array<std::array<char, 1080>, 1920> &&_img)
    {
        m_img = std::move(_img);
    }

    /*!
     * @brief This function returns a constant reference to member img
     * @return Constant reference to member img
     */
    inline eProsima_user_DllExport const std::array<std::array<char, 1080>, 1920>& img() const
    {
        return m_img;
    }

    /*!
     * @brief This function returns a reference to member img
     * @return Reference to member img
     */
    inline eProsima_user_DllExport std::array<std::array<char, 1080>, 1920>& img()
    {
        return m_img;
    }
    /*!
     * @brief This function sets a value in member tv_sec
     * @param _tv_sec New value for member tv_sec
     */
    inline eProsima_user_DllExport void tv_sec(uint32_t _tv_sec)
    {
        m_tv_sec = _tv_sec;
    }

    /*!
     * @brief This function returns the value of member tv_sec
     * @return Value of member tv_sec
     */
    inline eProsima_user_DllExport uint32_t tv_sec() const
    {
        return m_tv_sec;
    }

    /*!
     * @brief This function returns a reference to member tv_sec
     * @return Reference to member tv_sec
     */
    inline eProsima_user_DllExport uint32_t& tv_sec()
    {
        return m_tv_sec;
    }
    /*!
     * @brief This function sets a value in member tv_usec
     * @param _tv_usec New value for member tv_usec
     */
    inline eProsima_user_DllExport void tv_usec(uint32_t _tv_usec)
    {
        m_tv_usec = _tv_usec;
    }

    /*!
     * @brief This function returns the value of member tv_usec
     * @return Value of member tv_usec
     */
    inline eProsima_user_DllExport uint32_t tv_usec() const
    {
        return m_tv_usec;
    }

    /*!
     * @brief This function returns a reference to member tv_usec
     * @return Reference to member tv_usec
     */
    inline eProsima_user_DllExport uint32_t& tv_usec()
    {
        return m_tv_usec;
    }
    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    inline eProsima_user_DllExport void index(uint32_t _index)
    {
        m_index = _index;
    }

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    inline eProsima_user_DllExport uint32_t index() const
    {
        return m_index;
    }

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    inline eProsima_user_DllExport uint32_t& index()
    {
        return m_index;
    }

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const pic& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    std::array<std::array<char, 1080>, 1920> m_img;
    uint32_t m_tv_sec;
    uint32_t m_tv_usec;
    uint32_t m_index;
};

#endif // _PIC_H_