// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file err_code_msg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _COMMANDER_MSG_ERR_CODE_MSG_H_
#define _COMMANDER_MSG_ERR_CODE_MSG_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(err_code_msg_SOURCE)
#define err_code_msg_DllAPI __declspec( dllexport )
#else
#define err_code_msg_DllAPI __declspec( dllimport )
#endif // err_code_msg_SOURCE
#else
#define err_code_msg_DllAPI
#endif
#else
#define err_code_msg_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace commander_msg
{
    /*!
     * @brief This class represents the structure ErrCodeMsg defined by the user in the IDL file.
     * @ingroup ERR_CODE_MSG
     */
    class ErrCodeMsg
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport ErrCodeMsg();
        
        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~ErrCodeMsg();
        
        /*!
         * @brief Copy constructor.
         * @param x Reference to the object commander_msg::ErrCodeMsg that will be copied.
         */
        eProsima_user_DllExport ErrCodeMsg(const ErrCodeMsg &x);
        
        /*!
         * @brief Move constructor.
         * @param x Reference to the object commander_msg::ErrCodeMsg that will be copied.
         */
        eProsima_user_DllExport ErrCodeMsg(ErrCodeMsg &&x);
        
        /*!
         * @brief Copy assignment.
         * @param x Reference to the object commander_msg::ErrCodeMsg that will be copied.
         */
        eProsima_user_DllExport ErrCodeMsg& operator=(const ErrCodeMsg &x);
        
        /*!
         * @brief Move assignment.
         * @param x Reference to the object commander_msg::ErrCodeMsg that will be copied.
         */
        eProsima_user_DllExport ErrCodeMsg& operator=(ErrCodeMsg &&x);
        
        /*!
         * @brief This function copies the value in member err_code
         * @param _err_code New value to be copied in member err_code
         */
        inline eProsima_user_DllExport void err_code(const std::string &_err_code)
        {
            m_err_code = _err_code;
        }

        /*!
         * @brief This function moves the value in member err_code
         * @param _err_code New value to be moved in member err_code
         */
        inline eProsima_user_DllExport void err_code(std::string &&_err_code)
        {
            m_err_code = std::move(_err_code);
        }

        /*!
         * @brief This function returns a constant reference to member err_code
         * @return Constant reference to member err_code
         */
        inline eProsima_user_DllExport const std::string& err_code() const
        {
            return m_err_code;
        }

        /*!
         * @brief This function returns a reference to member err_code
         * @return Reference to member err_code
         */
        inline eProsima_user_DllExport std::string& err_code()
        {
            return m_err_code;
        }
        
        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(const commander_msg::ErrCodeMsg& data, size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
        
    private:
        std::string m_err_code;
    };
}

#endif // _COMMANDER_MSG_ERR_CODE_MSG_H_