// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Time.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Timer.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

commander_robot_msg::Time::Time()
{
    m_secs = 0;

    m_nsecs = 0;


}

commander_robot_msg::Time::~Time()
{
}

commander_robot_msg::Time::Time(const Time &x)
{
    m_secs = x.m_secs;
    m_nsecs = x.m_nsecs;
}

commander_robot_msg::Time::Time(Time &&x)
{
    m_secs = x.m_secs;
    m_nsecs = x.m_nsecs;
}

commander_robot_msg::Time& commander_robot_msg::Time::operator=(const Time &x)
{
    m_secs = x.m_secs;
    m_nsecs = x.m_nsecs;

    return *this;
}

commander_robot_msg::Time& commander_robot_msg::Time::operator=(Time &&x)
{
    m_secs = x.m_secs;
    m_nsecs = x.m_nsecs;

    return *this;
}

size_t commander_robot_msg::Time::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t commander_robot_msg::Time::getCdrSerializedSize(const commander_robot_msg::Time& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void commander_robot_msg::Time::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_secs;
    scdr << m_nsecs;
}

void commander_robot_msg::Time::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_secs;
    dcdr >> m_nsecs;
}

size_t commander_robot_msg::Time::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            



    return current_align;
}

bool commander_robot_msg::Time::isKeyDefined()
{
    return false;
}

void commander_robot_msg::Time::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
}
