// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Time.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _COMMANDER_ROBOT_MSG_TIME_H_
#define _COMMANDER_ROBOT_MSG_TIME_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Time_SOURCE)
#define Time_DllAPI __declspec( dllexport )
#else
#define Time_DllAPI __declspec( dllimport )
#endif // Time_SOURCE
#else
#define Time_DllAPI
#endif
#else
#define Time_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace commander_robot_msg
{
    /*!
     * @brief This class represents the structure Time defined by the user in the IDL file.
     * @ingroup TIME
     */
    class Time
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport Time();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~Time();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object commander_robot_msg::Time that will be copied.
         */
        eProsima_user_DllExport Time(const Time &x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object commander_robot_msg::Time that will be copied.
         */
        eProsima_user_DllExport Time(Time &&x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object commander_robot_msg::Time that will be copied.
         */
        eProsima_user_DllExport Time& operator=(const Time &x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object commander_robot_msg::Time that will be copied.
         */
        eProsima_user_DllExport Time& operator=(Time &&x);

        /*!
         * @brief This function sets a value in member secs
         * @param _secs New value for member secs
         */
        inline eProsima_user_DllExport void secs(uint32_t _secs)
        {
            m_secs = _secs;
        }

        /*!
         * @brief This function returns the value of member secs
         * @return Value of member secs
         */
        inline eProsima_user_DllExport uint32_t secs() const
        {
            return m_secs;
        }

        /*!
         * @brief This function returns a reference to member secs
         * @return Reference to member secs
         */
        inline eProsima_user_DllExport uint32_t& secs()
        {
            return m_secs;
        }
        /*!
         * @brief This function sets a value in member nsecs
         * @param _nsecs New value for member nsecs
         */
        inline eProsima_user_DllExport void nsecs(uint32_t _nsecs)
        {
            m_nsecs = _nsecs;
        }

        /*!
         * @brief This function returns the value of member nsecs
         * @return Value of member nsecs
         */
        inline eProsima_user_DllExport uint32_t nsecs() const
        {
            return m_nsecs;
        }

        /*!
         * @brief This function returns a reference to member nsecs
         * @return Reference to member nsecs
         */
        inline eProsima_user_DllExport uint32_t& nsecs()
        {
            return m_nsecs;
        }

        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(const commander_robot_msg::Time& data, size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

    private:
        uint32_t m_secs;
        uint32_t m_nsecs;
    };
}

#endif // _COMMANDER_ROBOT_MSG_TIME_H_