// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file msg_base.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MSG_BASE_H_
#define _MSG_BASE_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(msg_base_SOURCE)
#define msg_base_DllAPI __declspec( dllexport )
#else
#define msg_base_DllAPI __declspec( dllimport )
#endif // msg_base_SOURCE
#else
#define msg_base_DllAPI
#endif
#else
#define msg_base_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure msg_base defined by the user in the IDL file.
 * @ingroup MSG_BASE
 */
class msg_base
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport msg_base();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~msg_base();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object msg_base that will be copied.
     */
    eProsima_user_DllExport msg_base(const msg_base &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object msg_base that will be copied.
     */
    eProsima_user_DllExport msg_base(msg_base &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object msg_base that will be copied.
     */
    eProsima_user_DllExport msg_base& operator=(const msg_base &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object msg_base that will be copied.
     */
    eProsima_user_DllExport msg_base& operator=(msg_base &&x);

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    inline eProsima_user_DllExport void x(float _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    inline eProsima_user_DllExport float x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    inline eProsima_user_DllExport float& x()
    {
        return m_x;
    }
    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    inline eProsima_user_DllExport void y(float _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    inline eProsima_user_DllExport float y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    inline eProsima_user_DllExport float& y()
    {
        return m_y;
    }
    /*!
     * @brief This function sets a value in member theta
     * @param _theta New value for member theta
     */
    inline eProsima_user_DllExport void theta(float _theta)
    {
        m_theta = _theta;
    }

    /*!
     * @brief This function returns the value of member theta
     * @return Value of member theta
     */
    inline eProsima_user_DllExport float theta() const
    {
        return m_theta;
    }

    /*!
     * @brief This function returns a reference to member theta
     * @return Reference to member theta
     */
    inline eProsima_user_DllExport float& theta()
    {
        return m_theta;
    }

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const msg_base& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    float m_x;
    float m_y;
    float m_theta;
};

#endif // _MSG_BASE_H_