// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file msg_base.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "msg_base.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

msg_base::msg_base()
{
    m_x = 0.0;

    m_y = 0.0;

    m_theta = 0.0;


}

msg_base::~msg_base()
{
}

msg_base::msg_base(const msg_base &x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_theta = x.m_theta;
}

msg_base::msg_base(msg_base &&x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_theta = x.m_theta;
}

msg_base& msg_base::operator=(const msg_base &x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_theta = x.m_theta;

    return *this;
}

msg_base& msg_base::operator=(msg_base &&x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_theta = x.m_theta;

    return *this;
}

size_t msg_base::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t msg_base::getCdrSerializedSize(const msg_base& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void msg_base::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_x;
    scdr << m_y;
    scdr << m_theta;
}

void msg_base::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_x;
    dcdr >> m_y;
    dcdr >> m_theta;
}

size_t msg_base::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            




    return current_align;
}

bool msg_base::isKeyDefined()
{
    return false;
}

void msg_base::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
	 
}